version: "3.7"

services:

  webserver:
    image: nginx:alpine
    container_name: geolocalizer-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 20003:80
    environment:
      - SHELL=/bin/ash
    depends_on:
      - php-fpm

  php-fpm:
    build: .docker/php
    container_name: geolocalizer-php-fpm
    working_dir: /application
    volumes:
      - .:/application

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always

networks:
  default:
    external:
      name: nginx_proxy

